### ISSUE TITLE
Support Functions as DeletionPolicy/UpdateReplacePolicy Values

### ISSUE THREAD

**Issue by jthomerson** [aws-cloudformation/cfn-language-discussion#58]
Currently the `DeletionPolicy` attribute for any resource can only be a string. This means we can't use functions like `!If [ IsProduction, 'Retain', 'Delete' ]`.

I'd expect to be able to use conditions and other CloudFormation functions as a value for a `DeletionPolicy` the same as I can elsewhere in the template.

Others who have asked the same thing:

   * https://forums.aws.amazon.com/message.jspa?messageID=560586
   * https://github.com/aws/aws-cli/issues/3825

**Comment by PatMyron** [comment]
Workaround until proper support is having multiple duplicate resources with different policies and using [Conditions](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/conditions-section-structure.html) to create only resources with correct policies

**Comment by PatMyron** [comment]
@danieljamesscott due to [`AWS::Include` regional availability](https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/278), I've used [Jinja](https://www.palletsprojects.com/p/jinja/) to avoid maintaining duplicate source code

**Comment by PatMyron** [comment]
@danieljamesscott duplicate resources should have different Logical IDs
As @bdrx312 mentioned, painful workaround if you have resources with [DependsOn](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-dependson.html) because of that

And agreed, temporary workarounds are not to say this isn't still a most important feature request :)

**Comment by PatMyron** [comment]
@zetas [`AWS::Include` transform isn't fully supported by the Linter yet](https://github.com/aws-cloudformation/cfn-python-lint/issues/476), but workaround with [resource-level ignores](https://github.com/aws-cloudformation/cfn-python-lint#resource-based-metadata):


```yaml
  Instance:
    Type: AWS::RDS::DBInstance
    Metadata:
      cfn-lint:
        config:
          ignore_checks:
          - E3001
```

**Comment by lejiati** [comment]
Hi all, really appreciate all the feedback and I'm happy to share that intrinsic functions such as `Fn::If` is supported now with the launch of [AWS::LanguageExtensions transform](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/function-refs-in-policy-attributes.html). Please feel free to try it out and leave you feedback here.

**Comment by MalikAtalla-AWS** [comment]
This functionality is now available, so we can close this issue.

**Comment by lukepafford** [comment]
Hopefully this issue is just isolated to my environment. Let me know if anyone else experiences this problem with the new [AWS::LanguageExtensions Transform](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-languageextension-transform.html).

**Potential Bug** : When combining the transform with the `AWS::Serverless-2016-10-31` transform, only the first transform in the list is applied.



---
`AWS::Serverless-2016-10-31` listed first:
```
AWSTemplateFormatVersion: '2010-09-09'
Transform:
- AWS::Serverless-2016-10-31
- AWS::LanguageExtensions
```

Produces the error:
> Creating ChangeSet-2022-08-31T20-19-32Z in --- failed
    "StatusReason": "Transform AWS::Serverless-2016-10-31 failed with: Invalid Serverless Application Specification document. Number of errors found: 1. Structure of the SAM template is invalid. Every DeletionPolicy member must be a string."

This error occurs when creating the ChangeSet, indicating that the `AWS::LanguageExtensions` transform is being ignored.

---

`AWS::LanguageExtensions` listed first:
```
AWSTemplateFormatVersion: '2010-09-09'
Transform:
- AWS::LanguageExtensions
- AWS::Serverless-2016-10-31
```
Produces the error:
> Policy statement must contain actions. (Service: AmazonIdentityManagement; Status Code: 400; Error Code: MalformedPolicyDocument; Request ID: 9dcda1f8-0cbc-472d-891c-5e72378b500e; Proxy: null)

This error is referring to a role that previously deployed successfully, which **appears** to indicate that the `AWS::Serverless-2016-10-31` transform is being ignored.

---

If others can confirm that the `AWS::LanguageExtensions` transform plays nice with `AWS::Serverless-2016-10-31` then that will be helpful

**Comment by lejiati** [comment]
Hey @lukepafford , thank you for submitting this issue! The issue should be fixed now and please give it another try and let us know if you still have any questions.

**Comment by jlhood** [comment]
@lukepafford Note, you must put the `AWS::LanguageExtensions` transform before the `AWS::Serverless` transform in the list. We are working on updating [our documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-languageextension-transform.html) to indicate this ordering.

**Comment by benkehoe** [comment]
If this is known for AWS transforms, does it make sense for CloudFormation to even accept a template with the transforms out of order?

**Comment by jlhood** [comment]
@benkehoe Thanks for the feedback. We've had internal discussions on how to help guide customers here. First step is documentation. We're also [planning to add a rule to cfn-lint](https://github.com/aws-cloudformation/cfn-lint/issues/2346#issuecomment-1235550623) to check for this. We'll discuss the possibility of a server-side check.

**Comment by benkehoe** [comment]
ooh, adding it to cfn-lint is a great idea!

**Comment by lukepafford** [comment]
@jlhood @lejiati 
I confirmed that my fully uncommented [minimal template](https://github.com/aws-cloudformation/cfn-language-discussion/issues/58#issuecomment-1233391310) successfully deploys from both the `UPDATE_ROLLBACK_COMPLETE` state, and from a fresh deploy.

Thanks for the quick turnaround!

<img width="807" alt="Screen Shot 2022-09-09 at 12 49 26 AM" src="https://user-images.githubusercontent.com/19960230/189280288-19191fec-19ae-4c83-8728-c35157beafd0.png">
<img width="814" alt="Screen Shot 2022-09-09 at 12 49 51 AM" src="https://user-images.githubusercontent.com/19960230/189280337-c9063ffd-55a4-4137-9b6c-a22e8caddd04.png">
